### ISSUE TITLE
Colour helper functions

### ISSUE THREAD

**Issue by l2wilson94** [l2wilson94/Habitat#19]
It would be great if there were some functions available for Colour objects that let you adjust brightness/saturation/etc...

**Comment by Magnogen** [comment]
Would it work if there was a `Colour` object, that has lots of functions and things that change its colour, perhaps something like:

```js
var my_col = new Colour(Colour.Grey) // give it a colour that's already been made
my_col.red = 255 // change the red channel, keeping the green and blue the same
// or you could even do something like
my_col.hue = 0 // to keep the saturation and brightness
```

**Comment by l2wilson94** [comment]
I know I replied to you elsewhere, but just to keep a paper-trail, I'll respond here too:

I think having properties for HSL would be good! I'll make a new issue for that.

CMYK sounds interesting! I'm not sure I would ever need to use it though, as I don't usually print stuff off! But I have been thinking about making some TodePond stickers, so maybe this would be useful! I'll make a new issue for it too.

I would like to avoid using `new` and introducing new objects into this library - basically to stop myself from adding more complicated features. We already have the `Colour.make` function though that can make a simple colour object. The colour objects that it makes are intended to be immutable really. So I think it would be best to avoid using setters/getters to edit them and stuff. Instead, I think it would be good to make new colours from other colours. Not sure what the best syntax would be.

Is this really messy?
```js
const lightBlue = Colour.add(Colour.Blue, {lightness: 0.5})
```

**Comment by l2wilson94** [comment]
I've now refactored `colour.js`!

You now make colours by specifying a CSS `style` instead of `(r, g, b)`. So you can make colours in various ways. Behind the scenes, this is done by drawing on a tiny canvas, so didn't require too much code.
```js
const blue = Colour.make("rgb(0, 128, 255)")
const pink = Colour.make("hotpink")
const red = Colour.make("hsl(120, 100%, 50%)")
```

Colours also now have `hue`, `saturation` and `lightness` values that I calculate based on what this wiki page says: https://en.wikipedia.org/wiki/HSL_and_HSV#From_RGB

And you can `add` or `multiply` different colours together to make new colours.
```js
const darkBlue = Colour.add(Colour.Blue, {lightness: -20})
const lightBlue = Colour.multiply(Colour.Blue, {lightness: 1.3})
```

Full documentation here: https://todepond.gitbook.io/habitat/libraries/colour
